apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{.Values.mongo.name }}-pvc
  namespace: {{.Values.global.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{.Values.mongo.persistence.size }}
  {{- if.Values.mongo.persistence.storageClass }}
  storageClassName: {{.Values.mongo.persistence.storageClass }}
  {{- end }}
