apiVersion: v1
kind: Service
metadata:
  name: {{.Values.mongo.name }}-svc
  namespace: {{.Values.global.namespace }}
spec:
  selector:
    app: {{.Values.mongo.name }}
  ports:
    - protocol: TCP
      port: {{.Values.mongo.service.port }}
      targetPort: 27017
  type: ClusterIP
